---

- name: TEST
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 360
      register: output

    - debug:
        var: output
